### ISSUE TITLE
Manual install fails with gcc 8.2.0

### ISSUE THREAD

**Issue by doegox** [CIRCL/AIL-framework#279]
FTR the issues I got when trying to install manually on a Debian Sid during the hack.lu workshop:

ardb and its dependencies compile with `-Werror` but recent gcc 8.2.0 emits some new warnings which make compilation failing.

```
./installing_deps.sh
...
>>>>> Dowloading RocksDB
--2018-10-18 14:23:11--  https://github.com/facebook/rocksdb/archive/v5.14.2.tar.gz
...
>>>>> Building ROCKSDB
  CC       util/status.o
util/status.cc: In static member function ‘static const char* rocksdb::Status::CopyState(const char*)’:
util/status.cc:28:15: error: ‘char* strncpy(char*, const char*, size_t)’ output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
   std::strncpy(result, state, cch - 1);
   ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
util/status.cc:19:18: note: length computed here
       std::strlen(state) + 1; // +1 for the null terminator
       ~~~~~~~~~~~^~~~~~~
cc1plus: all warnings being treated as errors
```

Trying to remove `-Werror` from `AIL-framework/ardb/deps/rocksdb-5.14.2/Makefile` & `CMakeLists.txt`...
Failed else where, then trying to remove `-Werror` from `AIL-framework/ardb/src/Makefile` and it still failed elsewhere and I gave up, moving to the Docker install.

**Comment by SteveClement** [comment]
Thanks @doegox I have opened 2 issues in the ardb repo:

https://github.com/yinqiwen/ardb/issues/455
https://github.com/yinqiwen/ardb/issues/454

The quick and dirty fix is to compile with _gcc-7_ and bump rocksdb to 5.15.10 in **ardb/src/Makefile**

**Comment by blackswanburst** [comment]
Is this still ongoing?

**Comment by doegox** [comment]
no idea, not using it at the moment

**Comment by Rafiot** [comment]
`-Werror` is doing the trick, it's not great, but it works

**Comment by vitrvm** [comment]
I modified the Makefile (ardb/src/Makefile) Line 55 to 5.15.10, like @SteveClement said. Thanks
